language: node_js
node_js:
- 12
addons:
  ssh_known_hosts: 47.74.66.83
branches:
  only:
  - master
install:
- cd backend
- npm install
- cd ..
- cd frontend
- npm install
- cd ..
script:
- cd backend
- npm run test
- cd ..
before_install:
- openssl aes-256-cbc -K $encrypted_3b056051d907_key -iv $encrypted_3b056051d907_iv
  -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh www@gabrielndavid.live -o StrictHostKeyChecking=no 'cd ~/CarWash && ./deploy.sh'
